### ISSUE TITLE
docs/wiki/firmware-flasher suggestions

### ISSUE THREAD

**Issue by jawz101** [betaflight/betaflight.com#121]
https://github.com/betaflight/betaflight.com/blob/master/docs/wiki/configurator/firmware-flasher-tab.mdx

1. Under the "Other Options" section, can it be more descriptive about what DASHBOARD means?  Are we saying that you will not get an on-screen display unless you build it into the ROM?  Why would that not be a default option?
2. Under the "Custom Defines" section, `ACRO TRAINER` should be `ACRO_TRAINER`

**Comment by haslinghuis** [comment]
`DASHBOARD` depends on `OSD` and is providing an overall information page.

With firmware size overflowing we decided to provide a hardware base (core) build with features on top.
Please pick the required features which would not be available before.

**Comment by jawz101** [comment]
Is it the screen that comes up at the end of a flight when you disarm?

**Comment by haslinghuis** [comment]
No it's not the statistics screen :) - it's more of an overview screen

**Comment by jawz101** [comment]
lol ah.  `Post-Flight overview screen`.  I couldn't figure out how to word it.  But yeah, could the documenation say something like that?



Option | Description
-- | --
AKK (SA Fix) | Smartaudio patch for AKK hardware
DASHBOARD | OSD Dashboard
DASHBOARD | Post-flight Overview Screen

**Comment by jawz101** [comment]
Thanks.  I just submitted a pull request.  I didn't realize I could do that
