### ISSUE TITLE
docs/Development Intro page slack link not working

### ISSUE THREAD

**Issue by mqueme** [betaflight/betaflight.com#159]
![image](https://user-images.githubusercontent.com/1496976/221149147-03c9d267-631b-438f-831f-4d4e927c92fe.png)

This link leads to nothing.

![image](https://user-images.githubusercontent.com/1496976/221149256-0e8a106c-fcc4-4fb8-a288-c4f30b7f6cd7.png)

**Comment by haslinghuis** [comment]
Thanks for reporting. Will use as reminder as we need to remove slack as we have moved to Discord.

**Comment by sugaarK** [comment]
The slack is dead might be time to close it
