### ISSUE TITLE
Link to 4.4 release notes on website is broken in the release description on github

### ISSUE THREAD

**Issue by FPVian** [betaflight/betaflight.com#174]
### Describe the bug

This link is broken: [https://betaflight.com/docs/release/Betaflight%204.4%20Release%20Notes](https://betaflight.com/docs/release/Betaflight%204.4%20Release%20Notes)

### To Reproduce

Go to this link: [4.4.0 release](https://github.com/betaflight/betaflight/releases/tag/4.4.0) and try to click the link for release notes.

### Expected behavior

Expected to navigate here: [https://betaflight.com/docs/release/Betaflight-4.4-Release-Notes](https://betaflight.com/docs/release/Betaflight-4.4-Release-Notes)

### Support ID

```txt
n/a
```

### Flight controller

all

**Comment by haslinghuis** [comment]
Sorted now. Thanks for notifying.
