### ISSUE TITLE
A little blur with light theme

### ISSUE THREAD

**Issue by McGiverGim** [betaflight/betaflight.com#211]
Hi! The light theme seems to me that makes some texts a little blur. I don't know sure why, I suppose is the effect of the contrast with the background.

![image](https://github.com/betaflight/betaflight.com/assets/2673520/f6183887-4745-40d2-b9fa-4e8e45fb2d0b)

I'm the only one that thinks that is a little blur?

**Comment by haslinghuis** [comment]
On linux:
![image](https://github.com/betaflight/betaflight.com/assets/8344830/f4814569-424f-4464-8e89-b01dfda27b82)

**Comment by McGiverGim** [comment]
Where is the background? 😱

**Comment by haslinghuis** [comment]
¯\_(ツ)_/¯
 
 Same on windows (edge)

**Comment by haslinghuis** [comment]
Firefox on Windows:

![image](https://github.com/betaflight/betaflight.com/assets/8344830/18333b44-4a33-47d8-9c19-271c0e3f4e4e)

**Comment by haslinghuis** [comment]
![image](https://github.com/betaflight/betaflight.com/assets/8344830/54528605-beda-4c99-893f-c9a705739f1b)

**Comment by haslinghuis** [comment]
Only have 1366x768 and 1600x900 devices with me here for testing.

**Comment by McGiverGim** [comment]
I'm out of home. I will keep it open until I return and can do more tests.

**Comment by nerdCopter** [comment]
have not looked deeply, have to play with these things:
![image](https://github.com/betaflight/betaflight.com/assets/56646290/4bb1e8fc-2a08-499d-a3dd-b50737b8a515)

increasing blur px helped, but is the wrong solution. i feel like opacity might help, but do not immediately know where that "var" is set.

**Comment by McGiverGim** [comment]
The issue remains, but simply I don't know how to fix it.

**Comment by nerdCopter** [comment]
@VitroidFPV @freasy

**Comment by McGiverGim** [comment]
Keep on!

**Comment by VitroidFPV** [comment]
Will have a look

**Comment by ctzsnooze** [comment]
This is the Download page on Mac with Chrome.
Only Development and Download have the fancy background.
All the text is sharp.

 'You can find release planning here' is grey, and lacks contrast with the pale grey background.
 
 My main frustration is the lack of contrast between the orange text and grey backgrounds in daylight mode.  It's just too difficult to read. We probably need a darker orange, eg #c90.  This in HSL is a color angle of 45 degrees and luminance of 50.  I think our stock orange is #fc3 which is the same color angle, but luminance of 60..

**Comment by ctzsnooze** [comment]
@McGiverGim is it improved a little bit now?

**Comment by McGiverGim** [comment]
Yes it seems better now
![image](https://github.com/betaflight/betaflight.com/assets/2673520/c373322c-9e3c-4aa4-8643-195584555437)

I'm not sure if it's because the colours have changed or simply because the shade is at different position than in my first screen capture. But at this moment the issue is fixed for me.

**Comment by haslinghuis** [comment]
We also had missing commas in color definition for 750: 'rgb(44 44 44)',

Found in https://github.com/betaflight/betaflight.com/pull/288
