### ISSUE TITLE
Links for development boards are broken

### ISSUE THREAD

**Issue by YarosMallorca** [betaflight/betaflight.com#443]
https://betaflight.com/docs/development/Boards

In this link, all of the links to the developments return a 404.
Example: https://betaflight.com/docs/wiki/boards/SPRACINGF3MINI

**Comment by haslinghuis** [comment]
They were moved to boards archive in wiki section. F3 has been deprecated some time ago.

**Comment by haslinghuis** [comment]
Resolved in #444
