### ISSUE TITLE
Replace the outdated Video on the index page with Joshua Bardwells new Betaflight 4.3 Tutorial series

### ISSUE THREAD

**Issue by MrTucks** [betaflight/betaflight.com#73]
On the main page there is a section:
"Tutorial for beginners
Watch a tutorial video on how to get started"
it currently links to an old video by Joshua Bardwell about Betaflight 3.4. 

I think it should be replaced with a link to this playlist: https://www.youtube.com/playlist?list=PLwoDb7WF6c8nT4jjsE4VENEmwu9x8zDiE

**Comment by sugaarK** [comment]
Sorted
